spring.application.name=cabin-management-system


# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/cabin_management
spring.datasource.username=root
spring.datasource.password=root

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Server
server.port=8080

jwt.secret=MySuperSecretKeyForCabinManagementSystem123456789
jwt.expiration=86400000

logging.level.org.springframework.security=TRACE


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=manaschaudhary1602@gmail.com
spring.mail.password=waahohbqrswghlfm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
file.upload-dir=uploads

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB


office.start.time=10:30
office.end.time=19:30